### ISSUE TITLE
Use currently active split instead of bottom right

### ISSUE THREAD

**Issue by glebtv** [wincent/ferret#13]
Currently, when using splits, qickfix always appears on bottom-right split, and when opening files from quickfix it always opens in bottom-right split, and at start opens first file found in current split, so it replaces files in two open splits - current on search, and bottom right on switching files from quickfix.

I think you should do it like ctrl-p does - open at bottom of editor window or at bottom of currently active split, and open files in currently active split instead of bottom-right, and do not open first found file automatically (or at least make it configurable).

**Comment by glebtv** [comment]
Also, opening multiple found files simultaneously in multiple splits by clicking a split to make it active, then clicking a file from quickfix, is currently impossible. This would be a really nice feature

**Comment by sloria** [comment]
I agree--it would be excellent if ferret opened as a vertical split like ctrl-p. 2nd best would be to open at bottom of currently-active pane.

**Comment by wincent** [comment]
Sorry to be slow to comment on this one (was off having a baby).

What we're talking about here is overriding the native behavior of the quickfix window. I'd be fine with doing this if we can do so in a robust way. If either of you have any ideas for how this could be done please let me know; I haven't had much of a chance to think about it yet.

**Comment by cpixl** [comment]
Hmmm... I believe that using `bo cwindow` and `bo lwindow` instead of simply `cwindow` and `lwindow` on `private.vim` can make it similar to CtrlP behavior :)
Yeah... I'm feeling bad for being too lazy to send a pull request, but it worked on my installation of ferret.vim.

EDIT: Actually this is exactly how [CtrlP do this trick.](https://github.com/ctrlpvim/ctrlp.vim/blob/master/autoload/ctrlp.vim#L284)

**Comment by cpixl** [comment]
Okay... I'm not lazy today haha. Take a look at #19, I implemented exactly what I suggested.

**Comment by wincent** [comment]
https://github.com/wincent/ferret/pull/19 is now merged into `master`, so I am going to close this one.

@glebtv, if you feel like the other issues you mentioned (eg. "opening multiple found files simultaneously in multiple splits by clicking a split to make it active, then clicking a file from quickfix" and "do not open first found file automatically") are still worth tackling, please file separate issues for those.
