### ISSUE TITLE
ag --vimgrep is not working well

### ISSUE THREAD

**Issue by cpixl** [wincent/ferret#24]
When using `ag`, the `grepprg` is set to `ag --vimgrep` that outputs the same line multiple times if there is more than one match. The problem is that currently all lines are being highlighted in all matches... and it will conflict with #23, where the user won't be able to filter out some of the matches in the same line (`:Acks` will apply the changes in the entire line). Also the `ack` tool don't have the option to output the same line multiple times according to each match.

The point is, is `--vimgrep` really useful? It (currently) won't give a nice highlighting, won't work well with #23 `:Acks` and can't be reproduced when using `ack`.

**Comment by wincent** [comment]
Thanks! I'll comment on your PR (https://github.com/wincent/ferret/pull/23) to keep the commentary all in one place.

**Comment by noscripter** [comment]
I found the `--vimpgrep` option problematic too, coz sometimes the ag search fails on some keywords, but if I replace `ag --vimpgrep` with `ag` the search works fine again.

[related code](https://github.com/wincent/ferret/blob/master/plugin/ferret.vim#L16)

**Comment by wincent** [comment]
@noscripter, I am not sure why it would fail with `--vimgrep`. How exactly does it fail?

In any case, I can see why people might not like the behavior of `--vimgrep`. I'd be open to accepting a PR that made it optional (and probably on by default, for backwards compatibility?).

**Comment by noscripter** [comment]
I found this weird too, let me fiddle with the `--vimgrep` to see if anymore search fail occurs? I'll catch you up with furthermore reports about this.

**Comment by wincent** [comment]
Closing this one because `g:FerretExecutableArguments` has been added and it allows you to turn off `--vimgrep` or any other default options that you might not want.
