### ISSUE TITLE
replace words usage ?

### ISSUE THREAD

**Issue by mydearxym** [wincent/ferret#25]
love your work !

but when i want to replace something i get this (:Acks /foo/bar/ ):
![q](https://cloud.githubusercontent.com/assets/6184465/12004754/a6561d04-abae-11e5-9afd-496e5dcf55a0.png)

**Comment by wincent** [comment]
You would need to find the files first with `:Ack foo`. I think the error
message could be improved here to make this more obvious.

**Comment by mydearxym** [comment]
Got it , thanks !
