### ISSUE TITLE
old silversearcher does not support --vimgrep option

### ISSUE THREAD

**Issue by justrajdeep** [wincent/ferret#32]
Hi

I have the_silver_searcher version 0.24.1 (maintained my admin, cannot change)

it does not support `--vimgrep` option. Can you please remove it from your script?

**Comment by wincent** [comment]
No. I think a better solution here would be to check at runtime whether `--vimgrep` is supported, and if it is not, fall back to not using it. Care to submit a PR?

**Comment by justrajdeep** [comment]
Hi Wincent,

I am not that conversant with vim script, still i would like to give it a shot and submit a PR.
