### ISSUE TITLE
Ferret's autocommands clash with other plugins quickfix/loclist display settings

### ISSUE THREAD

**Issue by tdooner** [wincent/ferret#34]
Hey @wincent, I've got an issue with Ferret clashing with Neomake.

After some digging I've traced it to this autocommand:

https://github.com/wincent/ferret/blob/0b1c6b9ab55d7b4a4c8bcba3f976a488aa4b6be4/plugin/ferret.vim#L462

Without ferret, when I run `:Neomake` on saving a file, neomake fills the loclist with linter/build output and then [looks at some configuration](https://github.com/neomake/neomake/blob/c9fad67437f1c09ad24914695179f0c090624285/autoload/neomake.vim#L470-L484) to determine whether to call `lwindow` and with what argument. This allows users to disable the location list popping up, or to change its height.

Problem being, that ferret autocommand hook for `QuickFixCmdPost` is calling `lwindow` unconditionally, so the Neomake configuration settings have no effect.

Happy to attempt a PR for this, but wanted to ping you first to ask:
* Does it make sense to just run `lwindow` / `cwindow` in `ferret#private#complete` instead?
* Can the autocommand subscribers be scoped to some more-ferret-specific event names?

Thanks! And thanks for ferret, it's been really useful to me!

**Comment by wincent** [comment]
Thanks for bringing this up. We should fix it, although I can't give a very good answer right now (on my phone). In general we want to play nicely with other plug-ins by default, and when that's too hard, at least provide an option to override the behavior. Ideally, we don't make any breaking changes to Ferret requiring existing users to adjust their set-ups. Feel free to submit a PR, but if you don't I'll see what I can do about this.

**Comment by tdooner** [comment]
👍  Cool. To my eyes it looks like the `plugin/ferret.vim` autocommands are superfluous, since the window opens when the [finalize_search](https://github.com/wincent/ferret/blob/master/autoload/ferret/private/vanilla.vim#L10) method calls `cwindow`.

I'll make a PR to remove them fully realizing that I'm probably overlooking something. `:Ack`, `:Lack`, and `:Acks` seem to work.

**Comment by wincent** [comment]
Merged your PR to `next`. Thanks!
