### ISSUE TITLE
:Lack always opens results in quickfix window

### ISSUE THREAD

**Issue by regedarek** [wincent/ferret#47]
I experienced such a problem but don't know how to debug it yet.

Instead of location-list

I have newest neovim and ferret.

**Comment by skingtn** [comment]
Maybe you disabled Neovim loclists due to a snag I haven't hit yet, but is this solved by changing the second arg in private#lack() call to nvim#search() from 1 (qf) to 0 (loclist)?  Thanks for the plugin--it's light and works well.
