### ISSUE TITLE
:Back throws an error

### ISSUE THREAD

**Issue by regedarek** [wincent/ferret#48]
```:Back test```
always returns
```
Error detected while processing function ferret#private#back:
line    1:
E730: using List as a String
E116: Invalid arguments for function call
```
I have newest neovim and ferret.

**Comment by capelio** [comment]
As of 25 Oct 2017, using ferret `3.0.1` and Neovim `0.2.0` I also receive the same error when searching through buffers using the following leader:

`nmap <Leader>sb :Back<space>`

**Comment by wincent** [comment]
Thanks for confirming @capelio, and thanks for the initial report @regedarek. I can repro this, but I hadn't noticed as I very rarely use `:Back` myself. I'll see if I can get a fix ready.

**Comment by regedarek** [comment]
thank you wincent for all!

**Comment by capelio** [comment]
My thanks to you as well, @wincent, for the quick response and the awesome project :)
