### ISSUE TITLE
Multiple (> 2) words search doesn't work?

### ISSUE THREAD

**Issue by astyagun** [wincent/ferret#49]
![vim-ack-spaces](https://user-images.githubusercontent.com/158815/29672532-33465d08-88f5-11e7-9cf0-405278680743.gif)

I'm using MacVim (8.0.891) and `rg` (0.5.2). In `.vimrc` I have only this setting for Ferret: `let g:FerretMap = 0`.

**Comment by wincent** [comment]
Thanks for the report. Looks like a regression. Will figure out a fix.
