### ISSUE TITLE
Typo in ferret.vim:L62

### ISSUE THREAD

**Issue by ntnn** [wincent/ferret#5]
https://github.com/wincent/ferret/blob/master/plugin/ferret.vim#L62  
Second `FerretQFCommands` is `FerrerQFCommands`.

Also `get()` would be a reasonable use there, or are there reasons against it?

**Comment by wincent** [comment]
Great catch. Thanks. I was naughty and didn't manually test that one (and I haven't set up automated tests yet).

As for `get()`, I thought it only worked with lists and dictionaries, but I see that you can get it to work with the "global dictionary" by doing:

```
get(g:, 'SomeVariable', 'default')
```

Thanks for the tip!

**Comment by wincent** [comment]
Fixed the typo and switched to `get` (on the `master` branch). Thanks for contributing!
