### ISSUE TITLE
Small error in the documentation

### ISSUE THREAD

**Issue by teranex** [wincent/ferret#50]
In the mapping section the documentation says:

    Circumstances where mappings do not get set up ~
    ....
    - The mapping has been suppressed by setting |g:FerretMap| to 1 in your |.vimrc|.

But then the section explaining g:FerretMap seems to say the contrary to me. (0 is the correct value to disable the mappings)

    Controls whether to set up the Ferret mappings, such as |<Plug>(FerretAck)|
    (see |ferret-mappings| for a full list). To prevent any mapping from being
    configured, set to 0:
    >    let g:FerretMap=0

**Comment by wincent** [comment]
Thanks for pointing that out, @teranex. Will fix.
