### ISSUE TITLE
Exclude folders

### ISSUE THREAD

**Issue by Mte90** [wincent/ferret#54]
There is a way to exclude folders where ferret search?

**Comment by wincent** [comment]
Yes, depending on whether you are using `ack`, `ag`, `rg` etc, you can use various options, listed here: https://github.com/wincent/ferret/blob/b1ef0cf4af92c3a896821597d0d1a44b9c93dc5a/autoload/ferret/private.vim#L403-L491

For example, `--ignore-dir` for `ack`, `--ignore` for `ag` etc.

Autocompletion is available for these when using `:Ack` and the other commands.

**Comment by Mte90** [comment]
Cool, I searched for the term exclude instead ignore and missed that.
In the doc as I can see is not explained to configure them as global.
As example I want that hide stuff in the `vendor` folder but I don't want to write always the parameter.

**Comment by wincent** [comment]
@Mte90: since https://github.com/wincent/ferret/commit/09290a2a650cfd710d04a979a541b26a1c4dc048 there is a way to configure default options to be passed to the search executable. For the time being, you can set the options once, globally, at start-up time. If you had a need to set it on a per-directory or per-project basis (for example, via an autocmd), we would need to make some changes to make that possible.

**Comment by kinowarrior** [comment]
@wincent - I am using Ack, and wish to exclude the `tags` file in the base of all of my projects.

Currently when I search I get:

![with_tags](https://user-images.githubusercontent.com/49199497/58761936-a57b2880-8584-11e9-91f0-2d8a92044e39.gif)

My `vimrc` is basically:

```
    " search inside files using ripgrep. This plugin provides an Ack command.
    Plug 'wincent/ferret'
    let g:FerretHlsearch=0
    " search with ack for word under cursor
    nmap <leader>A <Plug>(FerretAckWord)
    " search & replace word based on previous search term with Ack
    nmap <leader>p <Plug>(FerretAcks)
```

I am unclear how to exclude by filename as per your helpful suggestions above. Would you please mind adding a one liner comment with a snippet that illustrates the solution. Thanks for this awesome plugin.

**Comment by kinowarrior** [comment]
I tried:

```
    let g:FerretExecutableArguments = {
    \   'ack': '--ignore-file=tags'
    \ }
```

But unfortunately it didn't work, the tags results were still present in the quickfix window.

**Comment by kinowarrior** [comment]
Ok, I solved this ON THE COMMAND LINE by creating a `~/.ackrc` file, and adding:

```
--ignore-file=is:tags
```

In case anyone interested, I used this [SOF answer](https://stackoverflow.com/a/17100054/1882064) and this template [ackrc file](https://gist.github.com/kevinold/4749656).

The [commit ](https://github.com/wincent/ferret/commit/09290a2a650cfd710d04a979a541b26a1c4dc048#diff-04c6e90faac2675aa89e2176d2eec7d8R282)highlighted above by wincent was also helpful in case just wishing to do this locally.

**Comment by kinowarrior** [comment]
Spoke too soon. This only works off the command line with `ack`.  Inside VIM using this plugin, the tags file is still being searched. Also:

```
    let g:FerretExecutableArguments = {
    \   'ack': '--ignore-file=is:tags'
    \ }
```
Does NOT work.  Please help!

**Comment by kinowarrior** [comment]
Final comment. My apologies on this one. Am using `ag` (silver searcher) under the covers despite the `:Ack` command (as per the README).  If I simply create a `.ignore` file, or else append `tags` to an existing `.gitignore` file then it suppresses the tags from appearing in search results.

This one was down to enduser error. Out.

**Comment by wincent** [comment]
@kinowarrior: yeah, adding it to the `.gitignore` is probably the easiest. I am not sure what the current status is with `.ignore` vs `.agignore` — it might be version and platform dependent, by the looks of issues like [this one](https://github.com/ggreer/the_silver_searcher/issues/1097).

**Comment by NICHTJ3** [comment]
If anyone else is wondering why they can't ignore files when using ag it appears to be caused by [this](https://github.com/ggreer/the_silver_searcher/issues/245)
