### ISSUE TITLE
How Do I use like this :Ack div | grep index

### ISSUE THREAD

**Issue by mycoolade** [wincent/ferret#56]
Hi. 
How do I command like Ack.vim or terminal Rg?

``` 
:Ack div | grep index 
Rg div | grep index
```

**Comment by wincent** [comment]
The Vim command line is not a shell so you can't use a pipe like that. Instead, you must provide a single search pattern like one of.the following:

```
:Ack div.+index
:Ack index.+div
```

Depending on the order of the words (you could also write the pattern in an order-independent way).

Usage is further described in the docs.

**Comment by mycoolade** [comment]
Ahh.. like on regex.
Got it. Thanx.
