### ISSUE TITLE
:Ack does not find strings after 4.0.0 update

### ISSUE THREAD

**Issue by kjivan** [wincent/ferret#59]
After the 4.0.0 update the :Ack command no longer finds strings that exists in files.

By the way; thanks for a great plugin!

Let me know if you need anymore info.

Environment:
OS: Ubuntu 16.04
Search executable: rg
vim:

> NVIM v0.3.1
> Build type: RelWithDebInfo
> LuaJIT 2.0.4
> Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fPIE -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-xZey2V/neovim-0.3.1/build/config -I/build/neovim-xZey2V/neovim-0.3.1/src -I/usr/include -I/build/neovim-xZey2V/neovim-0.3.1/build/src/nvim/auto -I/build/neovim-xZey2V/neovim-0.3.1/build/include
> Compiled by team+vim@tracker.debian.org
> 
> Features: +acl +iconv +jemalloc +tui
> See ":help feature-compile"
> 
>    system vimrc file: "$VIM/sysinit.vim"
>   fall-back for $VIM: "/usr/share/nvim"
> 
> Run :checkhealth for more info
>

**Comment by kjivan** [comment]
Seems to be an issue isolated to ripgrep. I installed the silver searcher and switch the executable to ag and it started working.

**Comment by kjivan** [comment]
Figured it out. I needed to update **ripgrep >= 0.8** when the no-config option was added. Which is need due to [this](https://github.com/wincent/ferret/commit/a6fcc785fa42ecd569fc83fce0a0ecf6ac0c0a99). 

It might be worth adding a min version comment to the readme or even better printing out a message in vim that the user should update the ripgrep.

**Comment by wincent** [comment]
Thanks for bringing this up. I think I can add some feature detection here to make this degrade gracefully with older versions of ripgrep.
