### ISSUE TITLE
ferret make <cword> not working.

### ISSUE THREAD

**Issue by lsaint** [wincent/ferret#64]
my vimrc:

` map <F4> :Ack! -w <cword><cr/>`

after i installed ferret,     `<cword> ` not working,  it can't expand to the word under cursor.

**Comment by wincent** [comment]
See [this section](https://github.com/wincent/ferret/blob/f6d7d01de8a92baee83218001c0bdbade8458a72/doc/ferret.txt#L309-L317) in the docs. Let me know if that doesn't help.

**Comment by lsaint** [comment]
it works, thanks.

**Comment by lsaint** [comment]
@wincent `<Plug>(FerretAckWord)` works well,  but i would like to match whole word only, like the `-w `arg in `Ack`, how should i do ?

**Comment by wincent** [comment]
If you look at [the definition](https://github.com/wincent/ferret/blob/f6d7d01de8a92baee83218001c0bdbade8458a72/plugin/ferret.vim#L713) of `<Plug>(FerretAckWord)` you'll see it just maps to:

    :Ack <C-r><C-w><CR>

And if you look at the Vim help (`:h c_CTRL-R_CTRL-W`) for `<C-r><C-w>` you'll see:

```
CTRL-R CTRL-F				*c_CTRL-R_CTRL-F* *c_<C-R>_<C-F>*
CTRL-R CTRL-P				*c_CTRL-R_CTRL-P* *c_<C-R>_<C-P>*
CTRL-R CTRL-W				*c_CTRL-R_CTRL-W* *c_<C-R>_<C-W>*
CTRL-R CTRL-A				*c_CTRL-R_CTRL-A* *c_<C-R>_<C-A>*
CTRL-R CTRL-L				*c_CTRL-R_CTRL-L* *c_<C-R>_<C-L>*
		Insert the object under the cursor:
			CTRL-F	the Filename under the cursor
			CTRL-P	the Filename under the cursor, expanded with
				'path' as in |gf|
			CTRL-W	the Word under the cursor
			CTRL-A	the WORD under the cursor; see |WORD|
			CTRL-L	the line under the cursor
```

so it is expanding the "word" under the cursor. You could make a similar mapping to instead find the "WORD". If neither of those gives you what you want, then you'd need to cook something else up, but for most intents and purposes, "word" should be pretty close to what `-w` does.
