### ISSUE TITLE
Autocompleting a directory does not include trailing slash

### ISSUE THREAD

**Issue by wincent** [wincent/ferret#69]
Because [this line](https://github.com/wincent/ferret/blob/d03f7ebeb0cea0311d23888adb1d62efcf04021a/autoload/ferret/private.vim#L666) does not include the slash.

**Comment by wincent** [comment]
cc @julien — hopefully [this](https://github.com/wincent/ferret/commit/24633d3047eb93013743b28b0ea735783c7850d9) works. At least it does in my cursory testing.

**Comment by julien** [comment]
@wincent works great thanks!
