### ISSUE TITLE
Search term highlighting

### ISSUE THREAD

**Issue by glebtv** [wincent/ferret#7]
Is it possible to get highlighting with ferret? ag-vim does this.

https://github.com/rking/ag.vim/blob/master/autoload/ag.vim#L139

**Comment by ntnn** [comment]
Please test [this PR](https://github.com/wincent/ferret/pull/8).

**Comment by wincent** [comment]
Thanks for the request @glebtv. I'll be merging that pull request and iterating from there, so I'm going to close this one.

**Comment by glebtv** [comment]
Works very nice :+1:
Thank you!
