### ISSUE TITLE
how to show full path ?

### ISSUE THREAD

**Issue by lsaint** [wincent/ferret#70]
![image](https://user-images.githubusercontent.com/896079/80700667-b162c800-8b10-11ea-86b6-e3ba252a42b8.png)

Recently，i updated my vim plugins and search result in quickfix show like this.
I checked my plugins and guess ferret may cause the change.
I google it and find nothing about it.
Anybody can do me a favor?  thanks

**Comment by wincent** [comment]
It's going to show the results [via the `:cexpr` command](https://github.com/wincent/ferret/blob/b1ef0cf4af92c3a896821597d0d1a44b9c93dc5a/autoload/ferret/private/shared.vim#L44) or similar, and IIRC it doesn't modify the paths it gets from the underlying search tool. So for example, if the underlying search tool is `rg`, it will end up executing [a command like](https://github.com/wincent/ferret/blob/24633d3047eb93013743b28b0ea735783c7850d9/autoload/ferret/private.vim#L742-L767) `rg --vimgrep --no-heading --no-config --max-columns 4096 your-search-pattern`, which will returns results relative to the current working directory.

Getting the search tool to output absolute paths is something I've not looked into; I think most of them probably don't provide an option for it, so you might have to create a wrapper that converts their relative paths to absolute paths. Even if you do that, it's possible that Vim may choose to show the result as relative to the current working directory; I don't know.

**Comment by jparise** [comment]
Possibly due to this change? https://github.com/romainl/vim-qf/commit/2e385e6d157314cb7d0385f8da0e1594a06873c5

**Comment by wincent** [comment]
@jparise Good hypothesis. Looks very likely, if the "c", "d" etc prefixes in @lsaint's screenshot are abbreviations.

**Comment by lsaint** [comment]
thank you guys. that 's what i looking for. sorry for my expression not so accurately.
