### ISSUE TITLE
Individual overrides

### ISSUE THREAD

**Issue by nomasprime** [wincent/ferret#74]
What's the best way to enable all [overrides](https://github.com/wincent/ferret#overrides) except `nocursorline`?

**Comment by wincent** [comment]
I think you just have to turn them all off (with `let g:FerretQFOverrides=0` in your `~/.vim/vimrc`) and then re-add the ones you want in your `~/.vim/ftplugin/qf.vim`.

[Ferret's overrides are here](https://github.com/wincent/ferret/blob/af83c2c7ab00b54dd164e9c5e55e31bac5a5a201/ftplugin/qf.vim#L20-L43), so you'd basically copy the bits out of that that you want.

**Comment by nomasprime** [comment]
Ah, OK, thought that might be the case.

Thanks.
