### ISSUE TITLE
Case insensitvie search

### ISSUE THREAD

**Issue by rjshrjndrn** [wincent/ferret#76]
Thanks for  this  awesome plugin. Is there any way to add case insensitve search. For example, 
`:Ack hello` should match both `Hello` and `heLLo`.

**Comment by wincent** [comment]
Yes. That depends on the underlying search tool that you're using.

For example, if you're using `ack`, `ag` or `rg`, then `:Ack -i hello` (or `:Ack hello -i`) would do what you want.

**Comment by wincent** [comment]
[This is a bit of a cheatsheet](https://github.com/wincent/ferret/blob/8ba03372738ad24a4ca9ce6452a5c8707fa64eb1/autoload/ferret/private.vim#L429-L516) showing (some of? most of?) the arguments that the different tools can take. Ferret will pass any arguments that you supply on to the underlying tool.

**Comment by rjshrjndrn** [comment]
My question was more of, how can I make case insensive default option?

**Comment by wincent** [comment]
@rjshrjndrn: You could do that with [`g:FerretExecutableArguments`](https://github.com/wincent/ferret#user-content-gferretexecutablearguments).
