### ISSUE TITLE
ripgrep 13.0.0 breaks search in neovim

### ISSUE THREAD

**Issue by nbardiuk** [wincent/ferret#78]
When I issue search command `:Ack a` it produces no output. I can see that rg is running in background with `pgrep -a rg`.

```
1272517 rg --vimgrep --no-heading a
```

When I try to search again it fails with error that it cannot cancel job.

```
Error detected while processing function ferret#private#ack[11]..ferret#private#nvim#search[1]..ferret#pri
vate#nvim#cancel:
line    3:
E474: Invalid argument
```

Looks like the cause of the problem is a change in rg https://github.com/BurntSushi/ripgrep/issues/1892

**Comment by nbardiuk** [comment]
As a workaround user can either 
* add `.` for path argument like `:Ack a .`
* dissable jobs with `let g:FerretNvim=0` and `let g:FerretJob=0`
* downgrade rg

**Comment by wincent** [comment]
Thanks for bringing this to my attention. Based on the issue, looks like the author wants changes in Neovim, which is unfortunate seeing as this appears to have broken many plug-ins, and even if Neovim does change, updating may be inconvenient or impossible for many users. So I think I probably need to implement a workaround.
