### ISSUE TITLE
nvim v0.7.0 error

### ISSUE THREAD

**Issue by lsaint** [wincent/ferret#84]
```
Caught: Vim(call):E16: Invalid range: call lfMru#record(s:Normalize(expand('<afile>:p'))) | call lfMru#recordBuffer(expand('<abuf>'))
Error detected while processing function ferret#private#nvim#close_cb[10]..ferret#private#shared#finalize_search:
line   32:
E16: Invalid range:     call s:set_title(l:post, 'Search `' . l:lastsearch . '`')
Press ENTER or type command to continue
Error detected while processing function ferret#private#nvim#close_cb:
line   10:
E171: Missing :endif
Press ENTER or type command to continue
Error detected while processing function <SNR>90_timer_callback:
line    9:
E16: Invalid range:     call timer_pause(a:timer_id, 1)
```
It would not occur in nvim 0.6.1 when searching.

**Comment by wincent** [comment]
Hi @lsaint. Anything special needed to reproduce this? What exact command are you running? Are you calling it from a mapping? What is the string/pattern you're searching for?

I do notice that the function at the top of the stack trace (`lfMru#record`) is _not_ from Ferret but from some other plug-in. Do you know what plug-in that is? Does the problem reproduce without it?

**Comment by lsaint** [comment]
> Hi @lsaint. Anything special needed to reproduce this? What exact command are you running? Are you calling it from a mapping? What is the string/pattern you're searching for?
> 
> I do notice that the function at the top of the stack trace (`lfMru#record`) is _not_ from Ferret but from some other plug-in. Do you know what plug-in that is? Does the problem reproduce without it?

Sorry about my indistinct expression.
It's a bit complex, seem like it involve to 3 plugin, [ferret](https://github.com/wincent/ferret),[ack.vim](https://github.com/mileszs/ack.vim) and [LeaderF](https://github.com/Yggdroot/LeaderF). All of them are working well on their own but got this error when I use them together.  
`lfMru#record` is from [LeaderF](https://github.com/Yggdroot/LeaderF)
the trigger action is from [ack.vim](https://github.com/mileszs/ack.vim)
and the error message is about [ferret](https://github.com/wincent/ferret) 


the reproduction step is:
nvim 0.7.0
use Ack! to find a keyword, then open a random file in the quick-fix window. the error will occur when I redo it a few times.

**Comment by wincent** [comment]
Thanks for the extra details @lsaint. To be honest, I'm not a user of those plug-ins, and I'm not very likely to have time to install them in order to trouble-shoot the interaction, but I would of course be open to reviewing a pull request if you or somebody else wanted to do some investigation and get to the bottom of it.

**Comment by lsaint** [comment]
got it. thanks.
