### ISSUE TITLE
:Ack shows 'Unknown option' warning in quickfix list in neovim

### ISSUE THREAD

**Issue by dsummersl** [wincent/ferret#9]
When I use `:Ack <search>` in nvim it shows the following warning at the end of the quicklist:

```
|| nvim: Unknown option argument: "--servername"
|| More info with "nvim -h"
```

`:Acks` and navigation seems to work fine tho...

**Comment by ntnn** [comment]
Thats an issue with popes vim-dispatch and neovim, if you turn off dispatch (`let g:FerretDispatch = 0`) it won't happen (and also not be working asynchronous). I've mentioned the same (and also that it then tends to not show the result in quickfix).

I also tended toward making a PR to use xolox' vim-misc async feature, if its available (it works great in neovim and I'm writing two plugins which are taking advantage of it).

**Comment by wincent** [comment]
Thanks for the report @dsummersl! I haven't used Neovim myself yet, so I'm looking for help ironing out issues like these. I do mean to dig into myself soon, but if you beat me to it I'd be happy to accept a PR.

Does this happen for all searches, even simple ones like `:Ack foo`?

Not sure where the `--servername` thing is coming from; it's not from Ferret itself.

**Comment by wincent** [comment]
> Thats an issue with popes dispatch.vim and neovim

Ah, thanks for shedding light on this, @ntnn. Do you think this is a bug in upstream dispatch.vim that we should report upstream?

**Comment by dsummersl** [comment]
Just figured out the vim-dispatch connection myself - yeah its happening with simple searches.

**Comment by ntnn** [comment]
@wincent Since dispatch itself works with neovim my best guess is that it's detection of the type of vim doesn't work with ferret, hence using the client/server architecture of vim - someone would need to take a look at that and see where exactly it fails.

@dsummersl Does it exclusively happen with simple searches or also with more complicated regexes?

**Comment by dsummersl** [comment]
Happens with regexes too.

**Comment by wincent** [comment]
It's just invoking dispatch.vim with  `:Make` (https://github.com/wincent/ferret/blob/ba51402eb8260b3883e8907b948cf1e0e0c54d76/autoload/ferret/private.vim#L81,L88).

**Comment by wincent** [comment]
Going to close this as I can't repro this with:
- NVIM 0.1.1 (compiled Jan  2 2016 22:49:49).
- Ferret 1.1.
- dispatch.vim current `HEAD` of `master` (eb3e564).
